#include "gui_internal.h"

void gui_install_style(void) {
    GtkCssProvider *provider;
    GdkScreen *screen;

    static const char *css =
        "GtkWindow, window { background-color: #0e1017; } "
        "GtkDialog, dialog, messagedialog { background-color: #141721; } "
        ".app-window { background-color: #0e1017; } "
        ".app-root { color: #f1f5f9; } "
        "label { color: #f1f5f9; } "
        "tooltip { background-color: #0c0e14; border: 1px solid #d99b26; border-radius: 6px; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.6); } "
        "tooltip label { color: #f8fafc; padding: 6px 10px; font-size: 12px; } "
        ".confirm-dialog-body { background-color: #161922; border: 1px solid #7f1d1d; border-radius: 10px; padding: "
        "16px; } "
        ".confirm-title { color: #fee2e2; font-weight: bold; font-size: 16px; } "
        ".confirm-message { color: #cbd5e1; font-size: 13px; } "
        ".confirm-icon-fallback { color: #fee2e2; background-color: #7f1d1d; border: 1px solid #ef4444; border-radius: "
        "999px; font-weight: bold; } "
        ".confirm-button-row { background-color: transparent; padding: 0 16px 16px 16px; } "
        "button { color: #f1f5f9; background-image: none; background-color: #1f2430; border: 1px solid #333c4f; "
        "border-radius: 8px; padding: 8px 14px; font-weight: bold; } "
        "button label { color: #f1f5f9; font-weight: bold; } "
        "button:hover { background-color: #282f3f; border-color: #d99b26; color: #ffffff; } "
        "button:hover label { color: #ffffff; } "
        "button:active { background-color: #323b4e; border-color: #f5b94e; } "
        "button:disabled, button:disabled label { color: #64748b; background-color: #12151d; border-color: #1f2533; } "
        "button.primary-button { color: #0b0d13; background-image: none; background-color: #d99b26; border-color: #f5b94e; font-weight: bold; "
        "} "
        "button.primary-button label { color: #0b0d13; font-weight: bold; } "
        "button.primary-button:hover { background-color: #e5a93c; border-color: #fed7aa; } "
        "button.primary-button:hover label { color: #0b0d13; } "
        "button.primary-button:disabled, button.primary-button:disabled label { color: #382a12; background-color: "
        "#7a5818; border-color: #614613; } "
        "button.ai-status-button, button.ai-status-button:disabled { color: #dcfce7; background-color: #143823; "
        "border-color: #22c55e; font-weight: bold; } "
        "button.ai-status-button label, button.ai-status-button:disabled label { color: #dcfce7; font-weight: bold; } "
        ".hint-button { background-color: #1f2430; border-color: #d99b26; } "
        ".hint-button label { color: #fcd34d; font-weight: bold; } "
        ".hint-button:hover { background-color: #2b2416; border-color: #fbbf24; color: #fef3c7; } "
        ".hint-button:hover label { color: #fef3c7; } "
        ".fullscreen-button { color: #e2e8f0; background-color: #181c26; border-color: #333c4f; border-radius: 8px; } "
        ".fullscreen-button label { color: #e2e8f0; font-weight: 500; } "
        ".fullscreen-button:hover { background-color: #232836; border-color: #d99b26; color: #ffffff; } "
        ".fullscreen-button:hover label { color: #ffffff; } "
        ".destructive-button { color: #fee2e2; background-color: #381616; border-color: #7f1d1d; border-radius: 8px; } "
        ".destructive-button label { color: #fee2e2; font-weight: bold; } "
        ".destructive-button:hover { background-color: #4c1d1d; border-color: #ef4444; color: #ffffff; } "
        ".destructive-button:hover label { color: #ffffff; } "
        "entry, spinbutton { color: #f8fafc; background-color: #0b0d13; border: 1px solid #2e374a; border-radius: 6px; "
        "padding: 7px 10px; font-family: monospace; font-size: 13px; font-weight: bold; } "
        "entry:focus, spinbutton:focus { border-color: #d99b26; box-shadow: inset 0 0 0 1px #d99b26; } "
        "entry:disabled, spinbutton:disabled { color: #64748b; background-color: #12151d; border-color: #1f2533; } "
        "radiobutton { color: #e2e8f0; } "
        "radiobutton label { color: #e2e8f0; font-weight: 500; } "
        ".panel, .menu-panel, .setup-group, .board-panel, .match-bar { background-color: #161922; border: 1px solid "
        "#282f3d; border-radius: 10px; box-shadow: 0 4px 18px rgba(0, 0, 0, 0.35); } "
        ".panel { padding: 14px; } "
        ".menu-panel { padding: 26px; } "
        ".setup-panel { padding: 22px; } "
        ".setup-group { padding: 14px; background-color: #10131b; border: 1px solid #1e2430; border-radius: 8px; } "
        ".history-card { background-color: #161922; } "
        ".move-entry-panel { background-color: #10131b; border: 1px solid #1e2430; border-radius: 8px; } "
        ".panel-title { color: #f1f5f9; font-weight: bold; font-size: 14px; } "
        ".app-title { color: #f8fafc; font-size: 22px; font-weight: bold; } "
        ".section-label { color: #cbd5e1; font-weight: bold; font-size: 12px; } "
        ".caption-label, .ai-summary, .coordinate-label, .match-meta { color: #94a3b8; font-size: 11px; } "
        ".coordinate-label { font-family: monospace; font-weight: bold; } "
        ".segmented-row, .action-row { background-color: transparent; } "
        ".clock-text { color: #d99b26; font-family: monospace; font-weight: bold; font-size: 13px; } "
        ".history-panel { background-color: #0b0d13; border: 1px solid #1e2430; border-radius: 6px; } "
        ".history-view, textview, textview text { color: #e2e8f0; background-color: #0b0d13; font-family: monospace; font-size: 12px; } "
        ".status-normal, .status-busy, .status-error, .status-success { border-radius: 6px; padding: 8px 12px; font-size: 12px; font-weight: 500; } "
        ".status-normal { color: #cbd5e1; background-color: #10131b; border: 1px solid #282f3d; } "
        ".status-busy { color: #dcfce7; background-color: #122b1a; border: 1px solid #22c55e; } "
        ".status-success { color: #ecfdf5; background-color: #102e1c; border: 1px solid #10b981; } "
        ".status-error { color: #fee2e2; background-color: #3b1414; border: 1px solid #ef4444; } "
        "button.format-help { background-color: #1f2430; border: 1px solid #333c4f; border-radius: 999px; padding: "
        "4px; min-width: 32px; min-height: 32px; color: #94a3b8; } "
        "button.format-help:hover { background-color: #282f3f; border-color: #d99b26; color: #d99b26; } "
        "button.format-help:active { background-color: #323b4e; border-color: #f5b94e; } "
        ".format-popover { background-color: #0b0d13; border: 1px solid #d99b26; border-radius: 8px; padding: 12px; box-shadow: 0 8px 24px rgba(0, 0, 0, 0.5); } "
        ".format-popover-title { color: #d99b26; font-weight: bold; font-size: 13px; } "
        ".format-popover-body { color: #cbd5e1; } "
        ".info-icon { color: #d99b26; font-weight: bold; } "
        ".match-bar { padding: 10px 14px; } "
        ".turn-banner { color: #fcd34d; font-size: 14px; font-weight: bold; padding: 6px 20px; border-radius: 999px; "
        "background-color: #231d11; border: 1px solid #d99b26; } "
        ".game-shell { background-color: transparent; } "
        ".sidebar { background-color: transparent; } "
        ".board-area { background-color: transparent; } "
        ".board-panel { background-color: #161922; padding: 16px; border: 1px solid #282f3d; border-radius: 10px; } "
        ".timer-label { color: #f1f5f9; font-family: monospace; font-weight: bold; font-size: 13px; } "
        ".board-frame { background-color: #0a0c10; border: 2px solid #4a3828; border-radius: 10px; padding: 8px; "
        "box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5); } "
        ".board-grid { background-color: #0a0c10; } "
        ".light-square { background-color: #e8e2d2; } "
        ".dark-square { background-color: #735237; } "
        ".piece-fallback { color: #171513; font-size: 28px; font-weight: bold; } "
        ".highlight-from { box-shadow: inset 0 0 0 3px #f59e0b, inset 0 0 12px rgba(245, 158, 11, 0.4); } "
        ".highlight-destination { box-shadow: inset 0 0 0 3px #10b981, inset 0 0 12px rgba(16, 185, 129, 0.35); } "
        ".highlight-selected { box-shadow: inset 0 0 0 3px #e5a93c, inset 0 0 14px rgba(229, 169, 60, 0.45); } "
        ".hint-from { box-shadow: inset 0 0 0 3px #06b6d4, inset 0 0 14px rgba(6, 182, 212, 0.45); } "
        ".hint-destination { box-shadow: inset 0 0 0 3px #eab308, inset 0 0 14px rgba(234, 179, 8, 0.45); } "
        ".move-input-valid { box-shadow: inset 0 0 0 2px #10b981; } "
        ".move-input-invalid { box-shadow: inset 0 0 0 2px #ef4444; } ";

    provider = gtk_css_provider_new();
    gtk_css_provider_load_from_data(provider, css, -1, NULL);
    screen = gdk_screen_get_default();
    if (screen != NULL) {
        gtk_style_context_add_provider_for_screen(screen, GTK_STYLE_PROVIDER(provider),
                                                  GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
    }
    g_object_unref(provider);
}
