#ifndef CHESS_ERROR_ERROR_CODE_H
#define CHESS_ERROR_ERROR_CODE_H

typedef enum {
    ERR_INVALID_INPUT,
    ERR_EMPTY_SELECTION,
    ERR_OPPONENT_PIECE,
    ERR_ILLEGAL_MOVE,
    ERR_UNRESOLVED_CHECK,
    ERR_UNDO_UNAVAILABLE,
    ERR_HINT_UNAVAILABLE,
    ERR_NOT_YOUR_TURN,
    ERR_TIME_UP,
    ERR_FATAL
} ErrorCode;

#endif
