# CPack archives the install graph and an explicitly filtered source tree.
if(EXISTS "${CMAKE_SOURCE_DIR}/SOURCE_REVISION")
    file(READ "${CMAKE_SOURCE_DIR}/SOURCE_REVISION" AC_SOURCE_COMMIT)
    string(STRIP "${AC_SOURCE_COMMIT}" AC_SOURCE_COMMIT)
else()
    find_package(Git QUIET)
    if(Git_FOUND)
        execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
            OUTPUT_VARIABLE AC_SOURCE_COMMIT OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
            OUTPUT_VARIABLE ac_dirty OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
        if(ac_dirty)
            string(APPEND AC_SOURCE_COMMIT "-dirty")
        endif()
    else()
        set(AC_SOURCE_COMMIT "unidentified")
    endif()
endif()
file(WRITE "${CMAKE_BINARY_DIR}/SOURCE_REVISION" "${AC_SOURCE_COMMIT}\n")
set(CPACK_PACKAGE_NAME "AnteaterChess-Reborn")
set(CPACK_PACKAGE_VERSION "${AC_VERSION}")
set(CPACK_PACKAGE_VENDOR "Team 22: DeepAnteater")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_SOURCE_DIR}/dist")
set(CPACK_PACKAGE_CHECKSUM SHA256)
set(CPACK_VERBATIM_VARIABLES TRUE)
if(WIN32)
    set(CPACK_GENERATOR ZIP)
    set(ac_platform windows-x64)
else()
    set(CPACK_GENERATOR TGZ)
    set(ac_platform linux-x64)
endif()
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${AC_VERSION}-${ac_platform}")
set(CPACK_SOURCE_GENERATOR TGZ)
set(CPACK_SOURCE_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${AC_VERSION}-source")
set(CPACK_SOURCE_IGNORE_FILES "/[.]git$;/[.]git/;/build/;/dist/;/bin/;/logs/;/__pycache__/;/[.]codex/;/[.]vscode/;/[.]idea/;/[.]cache/;/tests/output/;/tests/tmp/;[.]pyc$;CMakeUserPresets[.]json$;[.]log$;[.]tmp$;[.]swp$;[.]DS_Store$")
configure_file("${CMAKE_SOURCE_DIR}/cmake/PackageIdentity.cmake.in" "${CMAKE_BINARY_DIR}/PackageIdentity.cmake" @ONLY)
set(CPACK_PRE_BUILD_SCRIPTS "${CMAKE_BINARY_DIR}/PackageIdentity.cmake")
include(CPack)
