#ifndef CHESS_SYSTEM_SYSTEM_STATE_H
#define CHESS_SYSTEM_SYSTEM_STATE_H

typedef enum {
    INIT_STATE,
    MAIN_MENU_STATE,
    GAME_MODE_SELECTION_STATE,
    GAME_SETUP_STATE,
    GAMEPLAY_STATE,
    END_GAME_MENU_STATE,
    GAME_TERMINATION_STATE,
    EXIT_STATE
} SystemState;

#endif
